version: '3.8'

services:
  airflow:
    image: apache/airflow:2.8.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__FERNET_KEY=harshita
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__WEBSERVER__RBAC=true
      - AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC=10
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  mlflow:
    image: python:3.10-slim
    restart: always
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlflow_artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow_artifacts
      - ./mlflow_db:/mlflow_db
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=./mlflow_artifacts

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && airflow db init && airflow webserver --port 8080"

volumes:
  mlflow_db:
